-- 0271: schedule the daily CEO dashboard brief on pg_cron.
--
-- The موجز المدير التنفيذي card was only ever regenerated by hand (vercel.json
-- has no crons and no pg_cron job existed), so the dashboard served a frozen
-- brief — last successful run 2026-07-14, read as "today" two weeks later.
-- Mirror the satisfaction-refresh pattern: net.http_get against the app's cron
-- route, authenticated with the x-cron-secret header, both read from Vault.
--
-- Vault secrets (created out-of-band — never committed here):
--   ceo_brief_cron_url    = <app origin>/api/cron/ceo-brief
--   ceo_brief_cron_secret = the app's CRON_SECRET
--
-- 05:00 UTC = 08:00 Riyadh, after the 03:00-04:00 sync/snapshot crons so the
-- brief reads fresh Odoo data. The route itself renders + sends the WhatsApp
-- cards when the gateway is configured; the dashboard brief generation happens
-- first and no longer depends on it.

do $$
begin
  if exists (select 1 from cron.job where jobname = 'ceo-brief-daily') then
    perform cron.unschedule('ceo-brief-daily');
  end if;
end $$;

select cron.schedule(
  'ceo-brief-daily',
  '0 5 * * *',
  $cmd$
  select net.http_get(
    url := (select decrypted_secret from vault.decrypted_secrets where name = 'ceo_brief_cron_url'),
    headers := jsonb_build_object(
      'x-cron-secret',
      (select decrypted_secret from vault.decrypted_secrets where name = 'ceo_brief_cron_secret')
    ),
    timeout_milliseconds := 180000
  );
  $cmd$
);
